---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/locked_msg: Lock deployment in production
    flux.weave.works/locked_user: Alfonso Acosta <fons@syntacticsugar.consulting>
    fluxcd.io/tag.podinfod: glob:3.10.*
  name: podinfo
  namespace: demo
