apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-operator-az-values
  namespace: prometheus
  labels:
    app: prometheus-operator
data:
  values.yaml: |
    alertmanager:

      ingress:
        enabled: true

        annotations:
          kubernetes.io/ingress.class: nginx-internal
          nginx.ingress.kubernetes.io/rewrite-target: /$2

        hosts:
        - metrics-daa.dev-eks.acc1.central1.cc
        paths:
        - /alertmanager(/|$)(.*)
      alertmanagerSpec:
        externalUrl: https://metrics-daa.dev-eks.acc1.central1.cc/alertmanager

    grafana:

      ingress:
        enabled: true

        annotations:
          kubernetes.io/ingress.class: nginx-internal
          nginx.ingress.kubernetes.io/rewrite-target: /$2

        hosts:
        - metrics-daa.dev-eks.acc1.central1.cc

        path: /grafana(/|$)(.*)

      grafana.ini:
        server:
           root_url: https://metrics-daa.dev-eks.acc1.central1.cc/grafana

    prometheus:
      ingress:
        enabled: true

        annotations:
          kubernetes.io/ingress.class: nginx-internal
          nginx.ingress.kubernetes.io/rewrite-target: /$2

        hosts:
        - metrics-daa.dev-eks.acc1.central1.cc

        paths:
        - /prometheus(/|$)(.*)

      prometheusSpec:
        externalUrl: https://metrics-daa.dev-eks.acc1.central1.cc/prometheus
